// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf4-55X8UrtDwTI70Tzc3YzsRqaKqIQdU',
    appId: '1:145938289100:web:9e7d8d416aec831dc1cd69',
    messagingSenderId: '145938289100',
    projectId: 'loose-leaf-28a8a',
    authDomain: 'loose-leaf-28a8a.firebaseapp.com',
    storageBucket: 'loose-leaf-28a8a.firebasestorage.app',
    measurementId: 'G-0CX0X2GT2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNZrJyFdNT1xpWxIokPuY-xm3nfwP2j2o',
    appId: '1:145938289100:android:3c6e9655572539ccc1cd69',
    messagingSenderId: '145938289100',
    projectId: 'loose-leaf-28a8a',
    storageBucket: 'loose-leaf-28a8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQty-a8dxWbjP5oe7dCzjb3GyX8TnXk3I',
    appId: '1:145938289100:ios:109f56b2c040d541c1cd69',
    messagingSenderId: '145938289100',
    projectId: 'loose-leaf-28a8a',
    storageBucket: 'loose-leaf-28a8a.firebasestorage.app',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQty-a8dxWbjP5oe7dCzjb3GyX8TnXk3I',
    appId: '1:145938289100:ios:109f56b2c040d541c1cd69',
    messagingSenderId: '145938289100',
    projectId: 'loose-leaf-28a8a',
    storageBucket: 'loose-leaf-28a8a.firebasestorage.app',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf4-55X8UrtDwTI70Tzc3YzsRqaKqIQdU',
    appId: '1:145938289100:web:cd9e6cafb164b10ec1cd69',
    messagingSenderId: '145938289100',
    projectId: 'loose-leaf-28a8a',
    authDomain: 'loose-leaf-28a8a.firebaseapp.com',
    storageBucket: 'loose-leaf-28a8a.firebasestorage.app',
    measurementId: 'G-3EQYNXJKZ7',
  );
}
